spring:
    # DataSource Configuration
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://yorijori-db.cdxp4ultx56n.ap-northeast-2.rds.amazonaws.com:3306/ohjj
        username: yorijori
        password: yorijori-rds
    # JPA Configuration
    jpa:
        database: mysql
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create